# Generated by Django 4.0 on 2021-12-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_staff_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officepost',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='officepost',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='officepost',
            name='office',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='officepost',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Atualizado'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('lni-cog', 'Cog'), ('lni-stats-up', 'Graphic'), ('lni-users', 'Users'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Rocket')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=100, verbose_name='Serviços'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Atualizado'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.officepost', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Atualizado'),
        ),
    ]
