# Generated by Django 4.0 on 2021-12-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_officepost_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
    ]
